document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/select.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/calendar.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/multi-select.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/pager.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/ext-pager.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/tip.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/data-tree.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/lite-table.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/query-tab.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/pop.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/custom-checkboxs.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/input.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/validator.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/score.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/multi-calendar.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/drop-menu.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/condition.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/index-tab.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/forms.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/data-tree.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/input-tree.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/condition-plus.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/custom-table.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/cascade-select.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/ecui-plus.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/custom-tree.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/toolbar.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/custom-pager.js?v=" + globalTime + "'></script>");
document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/month-calender.js?v=" + globalTime + "'></script>");

// document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/condition-plus-ext.js?v=" + globalTime + "'></script>");
// document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/acct-input-tree.js?v=" + globalTime + "'></script>");
// document.writeln("<script src='"+ globalData.static +"js/ecui/src/ext/condition-plus-plus.js?v=" + globalTime + "'></script>");
